config/routes.rb
# -*- encoding : utf-8 -*-
AlteredBeast::Application.routes.draw do
  get '/session' => "sessions#create", :as => 'open_id_complete'

  resources :sites, :moderatorships, :monitorship

  resources :forums do
    resources :topics do
      resources :posts
      resource :monitorship
    end
    resources :posts
  end

  resources :posts do
    get :search, :on => :collection
  end
  resources :users do
    member do
      put :suspend, :make_admin, :unsuspend
      get :settings
      delete :purge
    end
    resources :posts, :only => [:index] do
#      get :monitored, :on => :collection, :shallow => true
    end
  end
  match '/users/:user_id/monitored(.:format)' => 'posts#monitored', :as => 'monitored_posts'

  match '/activate/:activation_code' => 'users#activate', :activation_code => nil, :as => 'activate'
  match '/signup' => 'users#new', :as => 'signup'
  match '/settings' => 'users#settings', :as => 'settings'
  match '/login' => 'sessions#new', :as => 'login'
  match '/logout' => 'sessions#destroy', :as => 'logout'
  match '/itex'  => 'itex#index'
  delete '/monitorship/:forum_id/:topic_id' => 'monitorships#destroy', :as => 'monitorship' 
  match '/monitorship/:forum_id/:topic_id' => 'monitorships#create', :as => 'monitorship' 

  resource  :session

  root :to => 'forums#index'
end

app/views/layouts/_footer.html.erb
<p class="disclaim">
  <strong>
  <% if site = current_site || Site.first %>
    <%= site.tagline %>
  <% end %>
  </strong>
</p>
<p style="clear:left;float:left;">
  <%# I18n.t 'txt.footer_message', :default => "Two's company. Three's a forum. More's a Beast." %>
</p>

app/views/layouts/_head.html.erb
<ul id="nav">
  <li><%= link_to I18n.t('txt.forums', :default => 'Forums'), root_path, :rel => 'home' %></li>
  <li><%= link_to I18n.t('txt.users', :default => 'Users'), users_path %></li>
  <li id="search">
    <%= form_tag posts_path, :method => 'get' do %>
      <%= text_field_tag :q, @q, :size => 15, :id => :search_box %>
    <% end %>
  </li>
  <li><%= link_to_function I18n.t('txt.search', :default => 'Search'), "", :href => root_path, :id => 'search-link' %></li>

  <% if current_site and logged_in? %>
  <li class="login"><%=  link_to current_user.display_name, user_path(current_user) %></li>
  <li class="logout"><%= link_to I18n.t('txt.settings', :default => 'Settings'), settings_path %></li>
  <li class="logout"><%= link_to I18n.t('txt.logout', :default => 'Logout'), logout_path(:to => CGI.escape(request.fullpath)) %></li>
  <% else %>
  <li><%= link_to I18n.t('txt.signup', :default => 'Signup'), signup_path(:to => CGI.escape(request.fullpath)) %></li>
  <li><%= link_to I18n.t('txt.login', :default => 'Login'), login_path(:to => CGI.escape(request.fullpath)) %></li>
  <% end %>
</ul>
<% name = (site = current_site || Site.first) && site.name %>
<h1><%= render 'layouts/svg_logo' %><%= link_to name || I18n.t('txt.beast_title', :default => 'Altered Beast'), root_path %></h1>

app/views/layouts/_svg_logo.html.erb
<span id="svg_logo"><svg id="svg_logo_svg" version="1.1" width="100%" height="100%" viewBox='0 -1 180 198' xmlns='http://www.w3.org/2000/svg'>
      <path id="svg_logo_path" fill="gold" stroke-width='0.5' stroke='#000' d='
        M170,60c4,11-1,20-12,25c-9,4-25,3-20,15c5,5,15,0,24,1c11,1,21,11,14,21c-10,15-35,6-48-1c-5-3-27-23-32-10c-1,13,15,10,22,16
        c11,4,24,14,34,20c12,10,7,25-9,23c-11-1-22-9-30-16c-5-5-13-18-21-9c-2,6,2,11,5,14c9,9,22,14,22,31c-2,8-12,8-18,4c-4-3-9-8-11-13
        c-3-6-5-18-12-18c-14-1-5,28-18,30c-9,2-13-9-12-16c1-14,12-24,21-31c5-4,17-13,10-20c-9-10-19,12-23,16c-7,7-17,16-31,15
        c-9-1-18-9-11-17c5-7,14-4,23-6c6-1,15-8,8-15c-5-6-57,2-42-24c7-12,51,4,61,6c6,1,17,4,18-4c2-11-12-7-21-8c-21-2-49-14-49-34
        c0-5,3-11,8-11C31,42,34,65,42,67c6,1,9-3,8-9C49,49,38,40,40,25c1-5,4-15,13-14c10,2,11,18,13,29c1,8,0,24,7,28c15,0,5-22,4-30
        C74,23,78,7,87,1c8-4,14,1,16,9c2,11-8,21-2,30c8,2,11-6,14-12c9-14,36-18,30,5c-3,9-12,19-21,24c-6,4-22,10-23,19c-2,14,15,2,18-2
        c9-9,20-18,33-22C159,52,166,54,170,60' />
    </svg></span>

app/views/layouts/application.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1 plus MathML 2.0 plus SVG 1.1//EN" "http://www.w3.org/2002/04/xhtml-math-svg/xhtml-math-svg-flat.dtd" >
<html xmlns="http://www.w3.org/1999/xhtml">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title><%= current_site && current_site.name || I18n.t('txt.beast_title', :default => 'Altered Beast') %><%= " - " + @page_title if @page_title %></title>
    <%= favicon_link_tag %>
    <%= stylesheet_link_tag 'application' %>
    <%= javascript_include_tag 'application' %>
<script type="text/x-mathjax-config">
  MathJax.Hub.Config({
    MathML: { useMathMLspacing: true },
    "HTML-CSS": { scale: 90,
                  extensions: ["handle-floats.js"]
       }
  });
</script>
<script type="text/javascript">
  if (!(Prototype.Browser.Gecko || navigator.userAgent.match(/MathPlayer/))) {
    var s = document.createElement('script');
    s.src = "<%= '/assets/MathJax/MathJax.js' %>?config=MML_HTMLorMML-full";
    document.querySelector('head').appendChild(s);
  };
</script>
    <% @feed_icons.each do |feed| %>
    <%= auto_discovery_link_tag :atom, feed[:url], :title => "Subscribe to '#{feed[:title]}'" %>
    <% end if @feed_icons.present? %>
    <%= csrf_meta_tag %>
  </head>
  <body>
    <div id="header">
      <%= render "layouts/head" %>
    </div>

    <div id="container">
      <div id="content">
        <%= flash_messages %>
        <%= yield %>
      </div>

      <div id="right">
        <%= yield(:right) %>
      </div>

      <br style="clear:both;" />
    </div>

    <div id="footer">
      <%= render "layouts/footer" %>
      <br style="clear:both;" />
    </div>
  </body>
</html>